* Encoding: UTF-8.
DATASET ACTIVATE DataSet1.
*Generalized Linear Mixed Models. 
GENLINMIXED
  /DATA_STRUCTURE SUBJECTS=Parent*Animal
  /FIELDS TARGET=AISlength TRIALS=NONE OFFSET=NONE
  /TARGET_OPTIONS DISTRIBUTION=NORMAL LINK=LOG
  /FIXED  EFFECTS=Genotype*Brainregion USE_INTERCEPT=TRUE
  /RANDOM EFFECTS=  Animal Age USE_INTERCEPT=TRUE COVARIANCE_TYPE=VARIANCE_COMPONENTS
  /BUILD_OPTIONS TARGET_CATEGORY_ORDER=ASCENDING INPUTS_CATEGORY_ORDER=ASCENDING 
    LCONVERGE=0.00000001(ABSOLUTE) MAX_ITERATIONS=100 CONFIDENCE_LEVEL=95 DF_METHOD=RESIDUAL
    SCORING=0 SINGULAR=0.000000000001
  /EMMEANS TABLES=Genotype COMPARE=Genotype CONTRAST=PAIRWISE
  /EMMEANS TABLES=Brainregion COMPARE=Brainregion CONTRAST=SIMPLE
  /EMMEANS_OPTIONS SCALE=ORIGINAL PADJUST=LSD.


DATASET ACTIVATE DataSet1.
*Generalized Linear Mixed Models. 
GENLINMIXED
  /DATA_STRUCTURE SUBJECTS=Parent*Animal
  /FIELDS TARGET=AISlength TRIALS=NONE OFFSET=NONE
  /TARGET_OPTIONS DISTRIBUTION=NORMAL LINK=LOG
  /FIXED  EFFECTS=Genotype Brainregion Genotype*Brainregion USE_INTERCEPT=TRUE
  /RANDOM EFFECTS=Animal USE_INTERCEPT=FALSE COVARIANCE_TYPE=VARIANCE_COMPONENTS SOLUTION=FALSE 
    /RANDOM EFFECTS=Parent USE_INTERCEPT=FALSE COVARIANCE_TYPE=VARIANCE_COMPONENTS SOLUTION=FALSE 
  /RANDOM EFFECTS=Age USE_INTERCEPT=FALSE COVARIANCE_TYPE=VARIANCE_COMPONENTS SOLUTION=FALSE 
  /BUILD_OPTIONS TARGET_CATEGORY_ORDER=ASCENDING INPUTS_CATEGORY_ORDER=ASCENDING 
    LCONVERGE=0.000001(ABSOLUTE)  MAX_ITERATIONS=100 CONFIDENCE_LEVEL=95 
    DF_METHOD=RESIDUAL COVB=MODEL SCORING=0 SINGULAR=0.000000000001
  /EMMEANS TABLES=Genotype COMPARE=Genotype CONTRAST=SIMPLE 
   /EMMEANS TABLES=Brainregion COMPARE=Brainregion CONTRAST=SIMPLE 
  /EMMEANS_OPTIONS SCALE=ORIGINAL PADJUST=LSD.

*Generalized Linear Mixed Models. 
GENLINMIXED
  /DATA_STRUCTURE SUBJECTS=Parent*Animal
  /FIELDS TARGET=AISlength TRIALS=NONE OFFSET=NONE
  /TARGET_OPTIONS DISTRIBUTION=NORMAL LINK=LOG
  /FIXED  EFFECTS=Genotype Brainregion Genotype*Brainregion USE_INTERCEPT=TRUE
  /RANDOM EFFECTS=Parent Animal Age USE_INTERCEPT=TRUE COVARIANCE_TYPE=VARIANCE_COMPONENTS 
    SOLUTION=True
  /BUILD_OPTIONS TARGET_CATEGORY_ORDER=ASCENDING INPUTS_CATEGORY_ORDER=ASCENDING 
    LCONVERGE=0.001(ABSOLUTE) HCONVERGE=0.001(RELATIVE) MAX_ITERATIONS=100 CONFIDENCE_LEVEL=95 
    DF_METHOD=RESIDUAL COVB=MODEL SCORING=0 SINGULAR=0.000000000001
