* Encoding: UTF-8.
*Generalized Linear Mixed Models. 
GENLINMIXED
  /DATA_STRUCTURE SUBJECTS=Parent*Genotype*Sample_ID*Brainregion
  /FIELDS TARGET=AISlength TRIALS=NONE OFFSET=NONE
  /TARGET_OPTIONS DISTRIBUTION=NORMAL LINK=LOG
  /FIXED  EFFECTS=Genotype Brainregion Genotype*Brainregion USE_INTERCEPT=True
  /RANDOM EFFECTS=Age SUBJECTS=Parent*Sample_ID USE_INTERCEPT=TRUE COVARIANCE_TYPE=VARIANCE_COMPONENTS
  /BUILD_OPTIONS TARGET_CATEGORY_ORDER=ASCENDING INPUTS_CATEGORY_ORDER=ASCENDING 
    LCONVERGE=0.0000001(ABSOLUTE) HCONVERGE=0.0000001(RELATIVE) MAX_ITERATIONS=100 CONFIDENCE_LEVEL=95 
    DF_METHOD=RESIDUAL COVB=ROBUST SCORING=0 SINGULAR=0.00000001
  /EMMEANS TABLES=Genotype*Brainregion COMPARE=Genotype CONTRAST=PAIRWISE
  /EMMEANS_OPTIONS SCALE=ORIGINAL PADJUST=SEQBONFERRONI.
